/* Copyright 2009 Google Inc. All Rights Reserved. */ (function(){var global=this;String.prototype.startsWith=function(a){return this.lastIndexOf(a,0)==0};String.prototype.trim=function(){return this.replace(/^\s+|\s+$/g,"")};if(!Function.prototype.apply)Function.prototype.apply=function(a,b){var c=[];a||(a=global);for(var d=b||[],e=0;e<d.length;e++)c[e]="args["+e+"]";c="oScope.__applyTemp__.peek()("+c.join(",")+");";if(!a.__applyTemp__)a.__applyTemp__=[];a.__applyTemp__.push(this);c=eval(c);a.__applyTemp__.pop();return c};
if(!Array.prototype.push)Array.prototype.push=function(){for(var a=0;a<arguments.length;a++)this[this.length]=arguments[a];return this.length};if(!Array.prototype.pop)Array.prototype.pop=function(){if(this.length){var a=this[this.length-1];this.length--;return a}};Array.prototype.peek=function(){return this[this.length-1]};if(!Array.prototype.shift)Array.prototype.shift=function(){if(this.length!=0){for(var a=this[0],b=0;b<this.length-1;b++)this[b]=this[b+1];this.length--;return a}};
if(!Array.prototype.unshift)Array.prototype.unshift=function(){for(var a=arguments.length,b=this.length-1;b>=0;b--)this[b+a]=this[b];for(b=0;b<a;b++)this[b]=arguments[b];return this.length};if(!Array.prototype.forEach)Array.prototype.forEach=function(a,b){for(var c=0;c<this.length;c++)a.call(b,this[c],c,this)};
function bind(a,b){var c=a.boundArgs_||[],c=c.concat(Array.prototype.slice.call(arguments,2));if(typeof a.boundSelf_!="undefined")b=a.boundSelf_;if(typeof a.boundFn_!="undefined")a=a.boundFn_;var d=function(){var d=c.concat(Array.prototype.slice.call(arguments));return a.apply(b,d)};d.boundArgs_=c;d.boundSelf_=b;d.boundFn_=a;return d}Function.prototype.bind=function(a){return bind.apply(null,[this,a].concat(Array.prototype.slice.call(arguments,1)))};var DB_mode=!1;function DumpError(a){try{throw a;}catch(b){DumpException(b)}}function DumpException(a,b){var c="Javascript exception: "+(b?b:"")+" "+a;BR_IsIE()&&(c+=" "+a.name+": "+a.message+" ("+a.number+")");var d="";if(typeof a=="string")d=a+"\n";else for(var e in a)try{d+=e+": "+a[e]+"\n"}catch(f){}d+=DB_GetStackTrace(DumpException.caller);DB_WriteDebugMsg(c+"\n"+d,1)}var function_name_re_=/function (\w+)/;
function DB_GetStackTrace(a){try{if(BR_IsNav())return Error().stack;if(!a)return"";var b;var c=function_name_re_.exec(String(a));b=c?c[1]:"";b="- "+b+"(";for(c=0;c<a.arguments.length;c++){c>0&&(b+=", ");var d=String(a.arguments[c]);d.length>40&&(d=d.substr(0,40)+"...");b+=d}b+=")\n";b+=DB_GetStackTrace(a.caller);return b}catch(e){return"[Cannot get stack trace]: "+e+"\n"}}var DB_starttime,DB_win=null,DB_winopening=!1;
function DB_WriteDebugMsg(a,b){if(DB_mode){try{var c=(new Date).getTime()-DB_starttime,d="["+c+"] "+HtmlEscape(a).replace(/\n/g,"<br>")+"<br>";b==1&&(d="<font color=#ff0000><b>Error: "+d+"</b></font>",DB_win.focus())}catch(e){}DB_WriteDebugHtml(d)}else typeof log!="undefined"&&log(HtmlEscape(a))}
function DB_WriteDebugHtml(a){if(DB_mode)try{if((DB_win==null||DB_win.closed)&&!DB_winopening)try{DB_winopening=!0;DB_win=window.open("","debug","width=700,height=500,toolbar=no,resizable=yes,scrollbars=yes,left=16,top=16,screenx=16,screeny=16");DB_win.blur();DB_win.document.open();DB_winopening=!1;var b="<font color=#ff0000><b>To turn off this debugging window,hit 'D' inside the main caribou window, then close this window.</b></font><br>";DB_WriteDebugHtml(b)}catch(c){}DB_win.document.write(a);DB_win.scrollTo(0,
1E6)}catch(d){}};function BR_AgentContains_(a){if(a in BR_AgentContains_cache_)return BR_AgentContains_cache_[a];return BR_AgentContains_cache_[a]=navigator.userAgent.toLowerCase().indexOf(a)!=-1}var BR_AgentContains_cache_={};function BR_IsIE(){return BR_AgentContains_("msie")&&!window.opera}function BR_IsSafari(){return BR_AgentContains_("safari")||BR_AgentContains_("konqueror")}function BR_IsNav(){return!BR_IsIE()&&!BR_IsSafari()&&BR_AgentContains_("mozilla")}var AssertTypeMap={string:String,number:Number,"boolean":Boolean};
function ShowElement(a,b){a.style.display=b?"":"none"}function HasClass(a,b){if(a==null||a.className==null)return!1;if(a.className==b)return!0;for(var c=a.className.split(" "),d=0;d<c.length;d++)if(c[d]==b)return!0;return!1}function AddClass(a,b){HasClass(a,b)||(a.className+=" "+b)}function RemoveClass(a,b){if(a.className!=null)if(a.className==b)a.className="";else{for(var c=a.className.split(" "),d=[],e=!1,f=0;f<c.length;f++)c[f]!=b?c[f]&&d.push(c[f]):e=!0;if(e)a.className=d.join(" ")}}
var getScrollTopGetters_={ieQuirks_:function(a){return a.document.body.scrollTop},ieStandards_:function(a){return a.document.documentElement.scrollTop},dom_:function(a){return a.pageYOffset}},getScrollLeftGetters_={ieQuirks_:function(a){return a.document.body.scrollLeft},ieStandards_:function(a){return a.document.documentElement.scrollLeft},dom_:function(a){return a.pageXOffset}};
function GetWindowPropertyByBrowser_(a,b){try{if(BR_IsSafari())return b.dom_(a);else if(!window.opera&&"compatMode"in a.document&&a.document.compatMode=="CSS1Compat")return b.ieStandards_(a);else if(BR_IsIE())return b.ieQuirks_(a)}catch(c){}return b.dom_(a)}var amp_re_=/&/g,lt_re_=/</g,gt_re_=/>/g;function HtmlEscape(a){if(!a)return"";return a.replace(amp_re_,"&amp;").replace(lt_re_,"&lt;").replace(gt_re_,"&gt;").replace(quote_re_,"&quot;")}var quote_re_=/\"/g;
function GetCursorPos(a,b){try{if(IsDefined(b.selectionEnd))return b.selectionEnd;else if(a.document.selection&&a.document.selection.createRange){var c=a.document.selection.createRange();if(c.parentElement()!=b)return-1;var d=c.duplicate();d.moveToElementText(b);d.setEndPoint("EndToStart",c);var e=d.text.length;if(e>b.value.length)return-1;return e}else return DB_WriteDebugMsg("Unable to get cursor position for: "+navigator.userAgent,0),b.value.length}catch(f){DumpException(f,"Cannot get cursor pos")}return-1}
function FindInArray(a,b){for(var c=0;c<a.length;c++)if(a[c]==b)return c;return-1}function IsDefined(a){return typeof a!="undefined"}function GetKeyCode(a){var b;if(a.keyCode)b=a.keyCode;else if(a.which)b=a.which;return b}function forid_1(a){return document.getElementById(a)}function forid_2(a){return document.all[a]}var forid=document.getElementById?forid_1:forid_2;
function log(a){try{if(window.parent!=window&&window.parent.log){window.parent.log(window.name+"::"+a);return}}catch(b){}var c=forid("log");c?(a="<p class=logentry><span class=logdate>"+new Date+"</span><span class=logmsg>"+a+"</span></p>",c.innerHTML=a+c.innerHTML):window.status=a};function AS_Assert(){}AS_Assert.raise=function(a){if(typeof Error!="undefined")throw Error(a||"Assertion Failed");else throw a;};AS_Assert.fail=function(a){a=a||"Assertion failed";typeof DumpError!="undefined"&&DumpError(a+"\n");AS_Assert.raise(a)};AS_Assert.isTrue=function(a,b){a||(b===void 0&&(b="Assertion failed"),AS_Assert.fail(b))};AS_Assert.equals=function(a,b,c){a!=b&&(c===void 0&&(c="AS_Assert.equals failed: <"+a+"> != <"+b+">"),AS_Assert.fail(c))};
AS_Assert.typeOf=function(a,b,c){if(typeof a!=b){if(a||a=="")try{if(b==AS_Assert.TYPE_MAP[typeof a]||a instanceof b)return}catch(d){}c===void 0&&(typeof b=="function"&&(c=b.toString().match(/^\s*function\s+([^\s\{]+)/))&&(b=c[1]),c="AS_Assert.typeOf failed: <"+a+"> not typeof "+b);AS_Assert.fail(c)}};AS_Assert.TYPE_MAP={string:String,number:Number,"boolean":Boolean};
AS_Assert.numArgs=function(a,b){var c=AS_Assert.numArgs.caller;c&&c.arguments.length!=a&&(b===void 0&&(b=c.name+" expected "+a+" arguments  but received "+c.arguments.length),AS_Assert.fail(b))};Function.prototype.bind=function(a){if(typeof this!="function")throw Error("Bind must be called as a method of a function object.");var b=this,c=Array.prototype.splice.call(arguments,1,arguments.length);return function(){for(var d=c.concat(),e=0;e<arguments.length;e++)d.push(arguments[e]);return b.apply(a,d)}};var listen;
(function(){function a(a){if(a.listen_hc_==null)a.listen_hc_=++d;return a.listen_hc_}function b(a){var b=Array.prototype.splice.call(arguments,1,arguments.length);return c[a].listener.apply(null,b)}var c={},d=0;listen=function(d,f,g,i){var h;h=f;var k=g,j=i,l=a(d),k=a(k),j=!!j;h=l+"_"+h+"_"+k+"_"+j;if(h in c)return h;j=b.bind(null,h);c[h]={listener:g,proxy:j,event:f,node:d,useCapture:i};if(d.addEventListener)d.addEventListener(f,j,i);else if(d.attachEvent)d.attachEvent("on"+f,j);else throw Error("Node {"+d+
"} does not support event listeners.");return h}})();function Point(a,b,c){this.x=a;this.y=b;this.coordinateFrame=c||null}Point.prototype.toString=function(){return"[P "+this.x+","+this.y+"]"};function Delta(a,b){this.dx=a;this.dy=b}Delta.prototype.toString=function(){return"[D "+this.dx+","+this.dy+"]"};function Rect(a,b,c,d,e){this.x=a;this.y=b;this.w=c;this.h=d;this.coordinateFrame=e||null}Rect.prototype.contains=function(a){return this.x<=a.x&&a.x<this.x+this.w&&this.y<=a.y&&a.y<this.y+this.h};
Rect.prototype.toString=function(){return"[R "+this.w+"x"+this.h+"+"+this.x+"+"+this.y+"]"};function nodeBounds(a){function b(b){for(var c=a.offsetParent;c&&c.offsetParent;c=c.offsetParent)c.scrollLeft&&(b.x-=c.scrollLeft),c.scrollTop&&(b.y-=c.scrollTop)}if(!a)return null;var c;c=a.ownerDocument&&a.ownerDocument.parentWindow?a.ownerDocument.parentWindow:a.ownerDocument&&a.ownerDocument.defaultView?a.ownerDocument.defaultView:window;if(a.getBoundingClientRect){var d=a.getBoundingClientRect();return new Rect(d.left+GetWindowPropertyByBrowser_(c,getScrollLeftGetters_),d.top+GetWindowPropertyByBrowser_(c,
getScrollTopGetters_),d.right-d.left,d.bottom-d.top,c)}if(a.ownerDocument&&a.ownerDocument.getBoxObjectFor)return d=a.ownerDocument.getBoxObjectFor(a),c=new Rect(d.x,d.y,d.width,d.height,c),b(c),c;for(var e=d=0,f=a;f.offsetParent;f=f.offsetParent)d+=f.offsetLeft,e+=f.offsetTop;c=new Rect(d,e,a.offsetWidth,a.offsetHeight,c);b(c);return c};var XH_ieProgId_,XH_ACTIVE_X_IDENTS$$inline_36=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"];
if(typeof XMLHttpRequest=="undefined"&&typeof ActiveXObject!="undefined"){for(var i$$inline_37=0;i$$inline_37<XH_ACTIVE_X_IDENTS$$inline_36.length;i$$inline_37++){var candidate$$inline_38=XH_ACTIVE_X_IDENTS$$inline_36[i$$inline_37];try{new ActiveXObject(candidate$$inline_38);XH_ieProgId_=candidate$$inline_38;break}catch(e$$inline_39){}}if(!XH_ieProgId_)throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed.");}
function XH_XmlHttpCreate(){return XH_ieProgId_?new ActiveXObject(XH_ieProgId_):new XMLHttpRequest}function XH_XmlHttpGET(a,b,c){a.open("GET",b,!0);a.onreadystatechange=c;XH_XmlHttpSend(a,null)}function XH_XmlHttpSend(a,b){try{a.send(b)}catch(c){throw log("XMLHttpSend failed "+c.toString()+"<br>"+c.stack),c;}};"undefined"==typeof log&&(log=function(){});function Dom(a){this.doc=a||document;this.getElementById_=this.doc.getElementById?function(a){return this.doc.getElementById(a)}:function(a){return this.doc.all[a]}}Dom.prototype.$=function(a){return this.getElementById_(a)};Dom.remove=function(a){AS_Assert.isTrue(a.parentNode);a.parentNode.removeChild(a)};Dom.insertAfter=function(a,b){AS_Assert.isTrue(b.parentNode);b.parentNode.insertBefore(a,b.nextSibling)};
Dom.insertBefore=function(a,b){AS_Assert.isTrue(b.parentNode);b.parentNode.insertBefore(a,b)};Dom.replace=function(a,b){AS_Assert.isTrue(b.parentNode);b.parentNode.replaceChild(a,b)};Dom.getInnerText=function(a){var b=[];Dom.getInnerTextHelp_(a,b);return b.join("")};Dom.getInnerTextHelp_=function(a,b){if(a.innerText)b.push(a.innerText);else if(a.data)b.push(a.data);else if(a.hasChildNodes())for(var c=a.firstChild;c;)arguments.callee(c,b),c=c.nextSibling};var DM_GlobalDom=new Dom;
function $(a){return DM_GlobalDom.$(a)};function PopupController(){this.activePopups_=[]}function _PC_Install(a){if(gPopupControllerInstalled)return!1;gPopupControllerInstalled=!0;a=a?a:document;listen(a.body,"mousedown",PC_notifyPopups);return!0}function PC_notifyPopups(a){if(gPopupController.activePopups_.length==0)return!1;for(var a=a||window.event,b=gPopupController.activePopups_.length-1;b>=0;--b){var c=gPopupController.activePopups_[b];PC_assertIsPopup(c);c.deactivate(a)&&gPopupController.activePopups_.splice(b,1)}return!0}
function PC_assertIsPopup(a){a:{var a=a.deactivate,b=Function,c="popup missing deactivate function";if(typeof a!=b){if(a||a=="")try{if(b==AssertTypeMap[typeof a]||a instanceof b)break a}catch(d){}var e=c===void 0;e&&(typeof b=="function"&&(c=b.toString().match(/^\s*function\s+([^\s\{]+)/))&&(b=c[1]),c="AssertType failed: <"+a+"> not typeof "+b);a=(a=c)||"Assertion failed";IsDefined(DumpError)&&DumpError(a+"\n");if(typeof Error!="undefined")throw Error(a||"Assertion Failed");else throw a;}}}
var gPopupController=new PopupController,gPopupControllerInstalled=!1;if(Array.prototype.indexOf==void 0)Array.prototype.indexOf=function(a){for(var b=0;b<this.length;++b)if(this[b]==a)return b;return-1};function DIT_forceProperTableWidth(){var a=$("confirmarea");if(a)a.style.display="none"};function DIT_hideID(a){ShowElement($(a),!1);return!1}function DIT_showID(a){ShowElement($(a),!0);return!1}function DIT_hideEl(a){ShowElement(a,!1);return!1}function DIT_showEl(a){ShowElement(a,!0);return!1}function DIT_showInstead(a,b){ShowElement($(a),!0);ShowElement(b,!1);return!1}
function DIT_showBelow(a,b,c,d){var e=$(a),f=nodeBounds(b),g=f.x,f=f.y+f.h;BR_IsIE()&&(g-=1,f-=2);BR_IsSafari()&&(g+=1);e.style.display="block";e.style.left="-2000px";a=="pop__dot"&&(g=g-e.offsetWidth+b.offsetWidth);c&&(g+=c);d&&(f+=d);e.style.left=g+"px";e.style.top=f+"px";a=new DIT_MyPopup(e);a.show();return!1}
function DIT_showRight(a,b,c,d){var a=$(a),b=nodeBounds(b),e=b.x+b.w,f=b.y,g=document.documentElement.clientWidth,i=document.documentElement.clientHeight,g={w:(window.innerWidth||g&&g>0?g:document.body.clientWidth)||1,h:(window.innerHeight||i&&i>0?i:document.body.clientHeight)||1};a.style.display="block";i=nodeBounds(a);e+i.w>g.w?(e=b.x-i.w,BR_IsIE()&&(e-=4,f-=2),BR_IsNav()&&(e-=2),BR_IsSafari()&&(e+=-1)):(BR_IsIE()&&(f-=2),BR_IsNav()&&(e+=2),BR_IsSafari()&&(e+=3));a.style.left="-2000px";a.style.position=
"absolute";c&&(e+=c);d&&(f+=d);a.style.left=e+"px";a.style.top=f+"px";c=new DIT_MyPopup(a);c.show();return!1}function DIT_closePopup(a){if(a=$(a))a.style.display="none"}var DIT_allColumnNames=[];function DIT_closeAllPopups(a){for(var b=0;b<DIT_allColumnNames.length;b++)DIT_closePopup("pop_"+b),DIT_closePopup("filter_"+b);DIT_closePopup("pop__dot");RemoveClass(a,"hover");return!1}function DIT_closeSubmenus(){for(var a=0;a<DIT_allColumnNames.length;a++)DIT_closePopup("filter_"+a);return!1}
function DIT_toggleHidden(a){for(;a;){if(HasClass(a,"closed"))return RemoveClass(a,"closed"),AddClass(a,"opened"),!1;if(HasClass(a,"opened"))return RemoveClass(a,"opened"),AddClass(a,"closed"),!1;a=a.parentNode}}function DIT_toggleCollapse(a){for(;a;){if(HasClass(a,"collapse"))return RemoveClass(a,"collapse"),AddClass(a,"expand"),!1;if(HasClass(a,"expand"))return RemoveClass(a,"expand"),AddClass(a,"collapse"),!1;a=a.parentNode}}
function DIT_showHidden(a){for(;a;){if(HasClass(a,"closed"))return RemoveClass(a,"closed"),AddClass(a,"opened"),!1;if(HasClass(a,"opened"))return!1;a=a.parentNode}}function DIT_toggleColumn(a){var b=$("colcontrol");HasClass(b,a)?RemoveClass(b,a):AddClass(b,a);return!1}function DIT_toggleRows(a){var b=$("colcontrol");AddClass(b,"hide_pri_groups");AddClass(b,"hide_mile_groups");AddClass(b,"hide_stat_groups");DIT_toggleColumn(a);return!1}var DIT_lastRolloverRow=void 0;
function DIT_rowRolloverOn(a){DIT_lastRolloverRow&&DIT_rowRolloverOff(DIT_lastRolloverRow);AddClass(a,"hover");DIT_lastRolloverRow=a;return!1}function DIT_rowRolloverOff(a){RemoveClass(a,"hover");return!1}function DIT_MyPopup(a){this._div=a;this._isVisible=!1}DIT_MyPopup.prototype.show=function(){this._div.style.display="block";this._isVisible=!0;a:{PC_assertIsPopup(this);for(var a=0;a<gPopupController.activePopups_.length;++a)if(this===gPopupController.activePopups_[a])break a;gPopupController.activePopups_.push(this)}};
DIT_MyPopup.prototype.hide=function(){this._div.style.display="none";this._isVisible=!1};
DIT_MyPopup.prototype.deactivate=function(a){if(this._isVisible){var b=0,c=0;if(a.pageX||a.pageY)b=a.pageX,c=a.pageY;else if(a.clientX||a.clientY)b=a.target?a.target:a.srcElement,c=b.ownerDocument&&b.ownerDocument.parentWindow?b.ownerDocument.parentWindow:window,b=a.clientX+GetWindowPropertyByBrowser_(c,getScrollLeftGetters_),c=a.clientY+GetWindowPropertyByBrowser_(c,getScrollTopGetters_);a=new Point(b,c,window);return nodeBounds(this._div).contains(a)?!1:(this.hide(),!0)}else return!0};
var DIT_rowToHighlight=void 0;function DIT_highlightRow(a){DIT_rowToHighlight=a;window.setTimeout("_highlightRowCallback()",10);return!1}function DIT_highlightRowCallback(){for(var a=DIT_rowToHighlight,b=a.checked;a&&a.tagName!="TR";)a=a.parentNode;b?AddClass(a,"selected"):RemoveClass(a,"selected")}
function DIT_floatMetadata(){var a=navigator.userAgent.toLowerCase();if(!(a.indexOf("firefox/1")!=-1||a.indexOf("firefox/2")!=-1||a.indexOf("seamonkey/1.1")!=-1)){var b=document.getElementById("meta-float"),c=document.getElementById("meta-container");window.attachEvent?window.attachEvent("onscroll",function(){DIT_floatVertically(b,c)}):window.addEventListener&&window.addEventListener("scroll",function(){DIT_floatVertically(b,c)},!1)}}
function DIT_floatVertically(a,b){var c=nodeBounds(a),d=nodeBounds(b),e=GetWindowPropertyByBrowser_(window,getScrollTopGetters_);if(!a.style.width)a.style.width=c.w+"px";if(e>d.y&&e-d.y+c.h<=b.style.top+d.h){if(a.style.position!="fixed")a.style.position="fixed",a.style.top="0",BR_IsIE()?a.parentNode.style.paddingRight=c.w+2+"px":a.parentNode.style.minWidth=c.w+"px"}else if(a.style.position!="relative"&&(a.style.position="relative",BR_IsIE()))a.parentNode.style.paddingRight=""}
var DIT_prefsXmlHttp=void 0;function DIT_setPeoplePrefs(a,b,c,d){DIT_prefsXmlHttp=XH_XmlHttpCreate();a=a?"/a/"+a:"";b=a+"/p/"+b+"/people/detailPrefs.do";d="perms_expanded="+c+"&token="+d;c=DIT_prefsXmlHttp;a=DIT_prefsFeedCallback;c.open("POST",b,!0);c.onreadystatechange=a;c.setRequestHeader("Content-Type","application/x-www-form-urlencoded");c.setRequestHeader("Content-Length",d.length);XH_XmlHttpSend(c,d)}function DIT_prefsFeedCallback(){};function DIT_selectAllIssues(){DIT_selectIssues(!0)}function DIT_selectNoneIssues(){DIT_selectIssues(!1)}function DIT_selectIssues(a){for(var b=$("resultstable"),c=0;c<b.rows.length;++c){var d=b.rows[c],e=d.cells[0];if(e.tagName=="TD")for(var f=0;f<e.childNodes.length;++f){var g=e.childNodes[f];if(g.tagName=="INPUT"&&g.type=="checkbox")g.checked=a?"checked":"",a?AddClass(d,"selected"):RemoveClass(d,"selected")}}}var DIT_nextFileID=1;
function DIT_addAttachmentFields(a){if(!(DIT_nextFileID>=16)){a=$(a);a.style.marginTop="4px";var b=document.createElement("div");b.innerHTML='<input type="file" name="file'+DIT_nextFileID+'" size=35 style="width:auto;margin-left:17px">&nbsp;<a style="font-size:x-small" href="#" onclick="this.parentNode.parentNode.removeChild(this.parentNode); return false">Remove</a> ';a.appendChild(b);++DIT_nextFileID;DIT_nextFileID<16?$("attachafile").innerHTML="Attach another file":$("attachprompt").style.display=
"none";$("attachmaxsize").style.display=""}}function DIT_openIssueUpdateForm(){DIT_showHidden($("makechangesarea"));document.location.hash="makechanges";DIT_forceProperTableWidth();window.setTimeout("document.getElementById('addCommentTextArea').focus();",100)}var DIT_currentPromptIndex=0;
function DIT_selectPrompt(a){DIT_showHidden($("prompt_edit_panel"));DIT_currentPromptIndex=a.value;var b=a=$("prompt_text_editor");if(HasClass(b,"undef"))RemoveClass(b,"undef"),b.value="";$("prompt_members_only_checkbox").checked=$("prompt_members_only_"+DIT_currentPromptIndex).value=="yes";$("prompt_summary_editor").value=$("prompt_summary_"+DIT_currentPromptIndex).value;$("prompt_summary_must_be_edited_checkbox").checked=$("prompt_summary_must_be_edited_"+DIT_currentPromptIndex).value=="yes";a.value=
$("prompt_text_"+DIT_currentPromptIndex).value;$("prompt_status_editor").value=$("prompt_status_"+DIT_currentPromptIndex).value;$("prompt_owner_editor").value=$("prompt_owner_"+DIT_currentPromptIndex).value;$("owner_defaults_to_member_checkbox").checked=$("owner_defaults_to_member_"+DIT_currentPromptIndex).value=="yes";$("owner_defaults_to_member_area").style.display=$("prompt_owner_editor").value?"none":"";for(a=0;a<15;a++)$("prompt_label_editor"+a).value=$("prompt_label_"+DIT_currentPromptIndex+
"_"+a).value;for(a=b=0;a<DIT_promptNames.length;a++)DIT_promptNames[a]!="<DELETED>"&&b++;b>1?$("delbtn").disabled="":$("delbtn").disabled="disabled"}var DIT_promptNames=[];
function DIT_newPrompt(){var a=DIT_promptNames.length,b=prompt("Name of new template?","");b.replace(/[&<>"]/g,"");if(b){for(var c=0;c<DIT_promptNames.length;c++)if(b==DIT_promptNames[c]){alert("Please choose a unique name.");return}var c=a,d=[];DIT_pushHiddenField(d,"prompt_name_"+c,"prompt_name_"+c,b);DIT_pushHiddenField(d,"prompt_members_only_"+c);DIT_pushHiddenField(d,"prompt_summary_"+c);DIT_pushHiddenField(d,"prompt_summary_must_be_edited_"+c);DIT_pushHiddenField(d,"prompt_text_"+c);DIT_pushHiddenField(d,
"prompt_status_"+c);DIT_pushHiddenField(d,"prompt_owner_"+c);DIT_pushHiddenField(d,"owner_defaults_to_member_"+c,"yes");DIT_pushHiddenField(d,"prompt_members_only_"+c);for(var e=0;e<15;e++)DIT_pushHiddenField(d,"prompt_label_"+c,"prompt_label_"+c+"_"+e);$("adminIssues").innerHTML+=d.join("");DIT_promptNames.push(b);$("prompt_menu").innerHTML+='<option value="'+a+'" selected=selected>'+b+"</select>";$("default_prompt_for_developers").innerHTML+='<option value="'+b+'">'+b+"</select>";$("default_prompt_for_users").innerHTML+=
'<option value="'+b+'">'+b+"</select>";DIT_selectPrompt($("prompt_menu"))}}function DIT_pushHiddenField(a,b,c,d){a.push('<input type=hidden name="',b,'"',' id="',c||b,'"',' value="',d||"",'"/>')}
function DIT_deletePrompt(){DIT_promptNames.splice(DIT_currentPromptIndex,1,"<DELETED>");$("prompt_name_"+DIT_currentPromptIndex).value="<DELETED>";DIT_toggleHidden($("prompt_edit_panel"));$("delbtn").disabled="disabled";for(var a=[],b=0;b<DIT_promptNames.length;b++)DIT_promptNames[b]!="<DELETED>"&&a.push("<option value="+b,">",DIT_promptNames[b],"</option>");$("prompt_menu").innerHTML=a.join("");DIT_rebuildDefaultPromptMenu("default_prompt_for_developers");DIT_rebuildDefaultPromptMenu("default_prompt_for_users")}
function DIT_rebuildDefaultPromptMenu(a){for(var b=$(a).value,c=[],d=0;d<DIT_promptNames.length;d++)DIT_promptNames[d]!="<DELETED>"&&(c.push('<option value="',DIT_promptNames[d],'"'),b==DIT_promptNames[d]&&c.push(' selected="selected"'),c.push(">",DIT_promptNames[d],"</option>"));$(a).innerHTML=c.join("")}
function DIT_switchPrompt(a,b,c){var d=!0;DIT_isDirty&&(d=confirm("Switching to a different template will lose the text you entered."));if(d)a=a?"/a/"+a:"",window.location=a+"/p/"+b+"/issues/entry?template="+c}
function DIT_savePrompt(){if(DIT_currentPromptIndex){$("prompt_members_only_"+DIT_currentPromptIndex).value=$("prompt_members_only_checkbox").checked?"yes":"";$("prompt_summary_"+DIT_currentPromptIndex).value=$("prompt_summary_editor").value;$("prompt_summary_must_be_edited_"+DIT_currentPromptIndex).value=$("prompt_summary_must_be_edited_checkbox").checked?"yes":"";$("prompt_text_"+DIT_currentPromptIndex).value=$("prompt_text_editor").value;$("prompt_status_"+DIT_currentPromptIndex).value=$("prompt_status_editor").value;
$("prompt_owner_"+DIT_currentPromptIndex).value=$("prompt_owner_editor").value;$("owner_defaults_to_member_"+DIT_currentPromptIndex).value=$("owner_defaults_to_member_checkbox").checked?"yes":"";$("owner_defaults_to_member_area").style.display=$("prompt_owner_editor").value?"none":"";for(var a=0;a<15;a++)$("prompt_label_"+DIT_currentPromptIndex+"_"+a).value=$("prompt_label_editor"+a).value}}
function DIT_toggleStar(a,b,c,d,e){var f=a.src.indexOf("star_off.gif")!=-1?1:0;a.src=f?"http://www.gstatic.com/codesite/ph/images/star_on.gif":"http://www.gstatic.com/codesite/ph/images/star_off.gif";a=d;DIT_starXmlHttp=XH_XmlHttpCreate();b=b?"/a/"+b:"";e=b+"/p/"+c+"/issues/setstar.do?alt=js&issueid="+a+"&starred="+f+"&cd="+(new Date).getTime()+"&token="+e;XH_XmlHttpGET(DIT_starXmlHttp,e,DIT_setStarCallback)}
function DIT_syncStarIcons(a,b){var c=document.getElementById(b);if(c)c.src=a.src;if(c=document.getElementById("vote_feedback"))c.innerHTML=a.src.indexOf("off.gif")!=-1?"Vote for this issue and get email change notifications.":"Your vote has been recorded."}var DIT_starXmlHttp=void 0;function DIT_setStarCallback(){DIT_starXmlHttp.readyState==4&&DIT_starXmlHttp.status==200&&DIT_gotSetStar(DIT_starXmlHttp.responseText)}
function DIT_gotSetStar(a){_d=null;try{eval("_d="+a)}catch(b){return alert("DIT: error parsing response of issue starring"),null}}function DIT_toggleStarLocal(a,b){var c=a.src.indexOf("star_off.gif")!=-1?1:0;a.src=c?"http://www.gstatic.com/codesite/ph/images/star_on.gif":"http://www.gstatic.com/codesite/ph/images/star_off.gif";$(b).value=""+c}var DIT_isDirty=!1;function DIT_dirty(){DIT_isDirty=!0}
function DIT_confirmDiscardUpdate(a){if(!DIT_isDirty||confirm("Discard your changes?"))document.location=a}function DIT_confirmDiscardEntry(){(!DIT_isDirty||confirm("Discard your changes?"))&&DIT_go("list")}
function DIT_exposeExistingLabelFields(a){if(($("label"+a+"3").value||$("label"+a+"4").value||$("label"+a+"5").value)&&$("addrow1"))DIT_showID(a+"row2"),DIT_hideID("addrow1");if($("label"+a+"6").value||$("label"+a+"7").value||$("label"+a+"8").value)DIT_showID(a+"row3"),DIT_hideID("addrow2");if($("label"+a+"9").value||$("label"+a+"10").value||$("label"+a+"11").value)DIT_showID(a+"row4"),DIT_hideID("addrow3");if($("label"+a+"12").value||$("label"+a+"13").value||$("label"+a+"14").value)DIT_showID(a+
"row5"),DIT_hideID("addrow4");if($("label"+a+"15").value||$("label"+a+"16").value||$("label"+a+"17").value)DIT_showID(a+"row6"),DIT_hideID("addrow5");if($("label"+a+"18").value||$("label"+a+"19").value||$("label"+a+"20").value)DIT_showID(a+"row7"),DIT_hideID("addrow6");if($("label"+a+"21").value||$("label"+a+"22").value||$("label"+a+"23").value)DIT_showID(a+"row8"),DIT_hideID("addrow7")}var DIT_firstEvent=!0;
function DIT_clearOnFirstEvent(){if(DIT_firstEvent)DIT_firstEvent=!1,$("summary").value=""}var DIT_novelStatuses=[],DIT_novelLabels=[];
function DIT_confirmNovelStatus(a){for(var b=a.value.trim().toLowerCase(),c=b!=="",d=DIT_statusWords,e=0;e<d.length&&c;++e){var f=d[e];b==f.toLowerCase()&&(c=!1)}c?(DIT_novelStatuses.indexOf(a)==-1&&DIT_novelStatuses.push(a),AddClass(a,"novel"),AddClass(a,"hasfocus")):(DIT_novelStatuses.indexOf(a)!=-1&&DIT_novelStatuses.splice(DIT_novelStatuses.indexOf(a),1),RemoveClass(a,"novel"));DIT_updateConfirmBeforeSubmit();return!0}
function DIT_confirmNovelLabel(a){var b=a.value.trim().toLowerCase();b.search("-")==0&&(b=b.substr(1));var c=b!=="";b.indexOf("?")>-1&&(c=!1);for(var d=DIT_labelWords,e=0;e<d.length&&c;++e){var f=d[e];b==f.toLowerCase()&&(c=!1)}c?(DIT_novelLabels.indexOf(a)==-1&&DIT_novelLabels.push(a),AddClass(a,"novel"),AddClass(a,"hasfocus")):(DIT_novelLabels.indexOf(a)!=-1&&DIT_novelLabels.splice(DIT_novelLabels.indexOf(a),1),RemoveClass(a,"novel"));DIT_updateConfirmBeforeSubmit();return!0}
var DIT_usedPrefixes={},DIT_labelFieldIDPrefix="",DIT_labelsBlockingSubmit=[];
function DIT_validateLabel(a){if(a!=void 0){DIT_confirmNovelLabel(a);var b=a;if(b.oldPrefix!=void 0){for(var c=DIT_usedPrefixes[b.oldPrefix],d=0;d<c.length&&c[d]!=b;)d++;c.splice(d,1)}c=b.value.split("-")[0].toLowerCase();DIT_usedPrefixes[c]==void 0?DIT_usedPrefixes[c]=[b]:DIT_usedPrefixes[c].push(b);b.oldPrefix=c;var b=[],e;for(e in DIT_usedPrefixes)if(c=DIT_usedPrefixes[e],c==void 0||c.length==0)delete DIT_usedPrefixes[e];else if(c.length>1&&FindInArray(DIT_exclPrefixes,e)!=-1){b.push(e);for(d=
0;d<c.length;d++){var f=c[d];AddClass(f,"exclconflict")}}else for(d=0;d<c.length;d++)f=c[d],RemoveClass(f,"exclconflict");if(b.length>0&&(e=DIT_restrict_to_known?"Error":"Warning",c=$("confirmarea")))$("confirmmsg").innerHTML=e+": Multiple values for: "+b.join(", "),c.className="exclconflict",c.style.display="";e=DIT_labelsBlockingSubmit.indexOf(a);a.value.indexOf("?")>-1&&e==-1?(DIT_labelsBlockingSubmit.push(a),AddClass(a,"questionmark")):a.value.indexOf("?")==-1&&e>-1&&(DIT_labelsBlockingSubmit.splice(e,
1),RemoveClass(a,"questionmark"));if(a=$("blocksubmitmsg"))a.innerHTML=DIT_labelsBlockingSubmit.length>0?'You must edit labels that contain "?".':""}}
function DIT_updateConfirmBeforeSubmit(){var a=DIT_restrict_to_known?"Error":"Note",b=DIT_restrict_to_known?"undefined":"uncommon",c="";DIT_novelStatuses.length>0&&DIT_novelLabels.length==1?c=a+": You are using an "+b+" status and an "+b+" label.":DIT_novelStatuses.length>0&&DIT_novelLabels.length>1?c=a+": You are using an "+b+" status and "+DIT_novelLabels.length+" "+b+" labels.":DIT_novelStatuses.length>0?c=a+": You are using an "+b+" status value.":DIT_novelLabels.length==1?c=a+": You are using an "+
b+" label.":DIT_novelLabels.length>1&&(c=a+": You are using "+DIT_novelLabels.length+" "+b+" labels.");if(a=$("confirmarea"))$("confirmmsg").innerHTML=c,c!=""?(a.className="novel",a.style.display=""):a.style.display="none"}
function DIT_MoreActions_onchange(a){switch(a.value){case "bulk":for(var b=[],c=0;c<issueIds.length;c++){var d=document.getElementById("cb_"+issueIds[c]);d&&d.checked&&b.push(issueIds[c])}b.length>0?(b=b.join(","),b="bulkedit?ids="+b,DIT_go(b+_ctxArgs)):alert("Please select some issues to edit");break;case "colspec":DIT_closeAllPopups(a),DIT_showID("columnspec")}a.value="moreactions"}var DIT_allOrigLabels=[];
function DIT_checkPlusOne(){var a=$("addCommentTextArea").value,b="\nPlease use the star icon instead.\nStars show your interest without annoying other users.";if(/^\s*[-+]+[0-9]+\s*.{0,30}$/m.test(a)&&a.length<150)return alert('This looks like a "+1" comment.'+b),!1;if(/^\s*me too.{0,30}$/i.test(a))return alert('This looks like a "me too" comment.'+b),!1;return!0}
function DIT_checkUnrestrict(a){for(var b=[],c=0;c<DIT_allOrigLabels.length;++c){var d=DIT_allOrigLabels[c];if(d.indexOf("Restrict-")==0){for(var e=!1,f=0;f<15;++f){var g=$("labeledit"+f).value;if(g==d){e=!0;break}}e||b.push(d)}}if(b.length==0)return!0;if(a)return a="You may not remove restriction labels.",alert(a),!1;a="You are removing these restrictions:\n   "+b.join("\n   ")+"\nThis may allow more people to access this issue.\nAre you sure?";return confirm(a)}
function DIT_addColumn(a){var b=DIT_getColspecElement();b.value=b.value+" "+a;$("colspecform").submit()}var DIT_lastSelectedRow=void 0;
function DIT_checkRangeSelect(a,b){var c=b.parentNode.parentNode.rowIndex;if(c!=DIT_lastSelectedRow){var d;d=(d=(d=a)?d:window.event?window.event:"")?d.modifiers?d.modifiers&Event.SHIFT_MASK:d.shiftKey:!1;if(d&&DIT_lastSelectedRow!=void 0){d=$("resultstable");for(var e=c>DIT_lastSelectedRow?1:-1,f=DIT_lastSelectedRow;f!=c;f+=e){var g=d.rows[f],i=b.checked;if(g){g.className=i?"selected":"";for(g=g.firstChild;g&&g.tagName!="TD";)g=g.nextSibling;if(g){for(g=g.firstChild;g&&g.tagName!="INPUT";)g=g.nextSibling;
if(g)g.checked=i}}}}DIT_lastSelectedRow=c}}function DIT_makeIssueLink(a){a="detail?id="+a;return a+_ctxArgs}function DIT_setRowLinks(){_ctxArgs=_formatContextQueryArgs();for(var a=$("resultstable"),b=1;b<a.rows.length;b++)for(var c=DIT_makeIssueLink(issueIds[b-1]),d=a.rows[b],e=0;e<d.cells.length;e++)for(var f=d.cells[e],f=f.firstChild;f;f=f.nextSibling)if(f.tagName=="A"){f.href=c;break}}
function DIT_toggleColumnUpdate(a){for(var b=DIT_getColspecElement().value.split(" "),c=[],d=0;d<b.length;d++)_allColumnNames[a]!=b[d].toLowerCase()&&c.push(b[d]);DIT_getColspecElement().value=c.join(" ");DIT_getSearchColspecElement().value=c.join(" ");DIT_toggleColumn("hide_col_"+a);DIT_setRowLinks()};var DIT_labelStore,DIT_searchStore,DIT_exclPrefixes=[],DIT_statusStore,DIT_memberListStore,DIT_ownerStore,DIT_autoCompleteStore,DIT_restrict_to_known,DIT_autoCompleteFeedName;function DIT_fullComplete(a,b){if(!a.startsWith("*"))return null;for(var c=[],d=0;d<b.length;d++)c.push(new _AC_Completion(b[d].name,b[d].name,b[d].doc));return c}var DIT_statusWords=[];
function DIT_setUpStatusStore(a,b){var c={};DIT_statusWords=[];for(var d=0;d<a.length;d++){var e=a[d];DIT_statusWords.push(e.name);c[e.name]=e.doc}for(d=0;d<b.length;d++)e=b[d],DIT_statusWords.push(e.name),c[e.name]=e.doc;DIT_statusStore=new _AC_SimpleStore(DIT_statusWords);DIT_statusStore.docstrings=c;DIT_statusStore.commaCompletes=!1;DIT_statusStore.substitute=function(a,b,c,d){return d.value};DIT_statusStore.completable=function(a){if(!ac_everTyped)return"*status";return a};DIT_statusStore.completions=
function(c,d){var e;e=a;var h=b;if(c.startsWith("*")){var k=[];k.push({heading:"Open Statuses:"});for(var j=0;j<e.length;j++)k.push(new _AC_Completion(e[j].name,e[j].name,e[j].doc));k.push({heading:"Closed Statuses:"});for(j=0;j<h.length;j++)k.push(new _AC_Completion(h[j].name,h[j].name,h[j].doc));e=k}else e=null;if(e)return e;return _AC_SimpleStore.prototype.completions.call(this,c,d)}}function DIT_addACItem(a,b,c,d){a.push(c);b[c]=d}
function DIT_addACItemList(a,b,c,d,e,f){for(var g,i=0;i<d.length;i++){var h=d[i];g=c+h.name;e&&(g=g.replace(e,f));DIT_addACItem(a,b,g,h.doc)}}
function DIT_setUpSearchStore(a,b,c,d){for(var e=[],f={},g=[],i=[],h=0;h<a.length;h++){var k=a[h];k.name.indexOf("-")==-1?i.push(k):g.push(k)}DIT_addACItemList(e,f,"",g,"-","=");DIT_addACItemList(e,f,"label:",i);DIT_autoCompleteFeedName=="issueOptions"&&(DIT_addACItem(e,f,"owner:me","Issues owned by me"),DIT_addACItem(e,f,"cc:me","Issues that CC me"),DIT_addACItem(e,f,"reporter:me","Issues I reported"),DIT_addACItemList(e,f,"owner:",b),DIT_addACItemList(e,f,"cc:",b),DIT_addACItemList(e,f,"reporter:",
b),DIT_addACItemList(e,f,"status:",c),DIT_addACItemList(e,f,"status:",d));DIT_addACItem(e,f,"is:starred","Starred by me");DIT_addACItem(e,f,"summary:","Search within the summary field");DIT_autoCompleteFeedName=="issueOptions"?(DIT_addACItem(e,f,"commentby:me","Issues that I commented on"),DIT_addACItemList(e,f,"commentby:",b),DIT_addACItem(e,f,"attachment:","Search within attachment names"),DIT_addACItem(e,f,"is:open","Issues that are open"),DIT_addACItem(e,f,"has:owner","Issues with some owner"),
DIT_addACItem(e,f,"has:attachment","Issues with some attachments"),DIT_addACItem(e,f,"id:1,2,3","Match only the specified issues"),a=new Date,a=a.getFullYear()+"/"+(a.getMonth()+1)+"/"+a.getDate(),DIT_addACItem(e,f,"opened-after:today-1","Opened within the last N days"),DIT_addACItem(e,f,"opened-after:"+a,"Opened after the specified date"),DIT_addACItem(e,f,"opened-before:today-1","Opened more than N days ago"),DIT_addACItem(e,f,"opened-before:"+a,"Opened before the specified date"),DIT_addACItem(e,
f,"modified-after:today-1","Modified within the last N days"),DIT_addACItem(e,f,"modified-after:"+a,"Modified after the specified date"),DIT_addACItem(e,f,"modified-before:today-1","Modified more than N days ago"),DIT_addACItem(e,f,"modified-before:"+a,"Modified before the specified date"),DIT_addACItem(e,f,"closed-after:today-1","Closed within the last N days"),DIT_addACItem(e,f,"closed-after:"+a,"Closed after the specified date"),DIT_addACItem(e,f,"closed-before:today-1","Closed more than N days ago"),
DIT_addACItem(e,f,"closed-before:"+a,"Closed before the specified date")):DIT_autoCompleteFeedName=="wikiOptions"?(DIT_addACItem(e,f,"pagename:","Search with page names"),DIT_addACItem(e,f,"commentby:me","Pages that I commented on"),DIT_addACItem(e,f,"changedby:","Last changed by the specified user")):DIT_autoCompleteFeedName=="downloadOptions"&&(DIT_addACItem(e,f,"filename:","Search within file names"),DIT_addACItem(e,f,"uploadedby:","Files uploaded by the specified user"));DIT_searchStore=new _AC_SimpleStore(e);
DIT_searchStore.docstrings=f;DIT_searchStore.substitute=function(a,b,c,d){for(var e=b;a.charAt(e)!=" "&&e<a.length;)e++;for(;a.charAt(e)==" "&&e<a.length;)e++;return a.substring(0,b-c.length)+d.value+" "+a.substring(e)};DIT_searchStore.autoselectFirstRow=function(){return!1}}
function DIT_setUpMemberStore(a){for(var b=[],c={},d=0;d<a.length;d++){var e=a[d];b.push(e.name);c[e.name]=e.doc}DIT_memberListStore=new _AC_SimpleStore(b);DIT_memberListStore.docstrings=c;DIT_memberListStore.completions=function(b,c){var d=DIT_fullComplete(b,a);if(d)return d;return _AC_SimpleStore.prototype.completions.call(this,b,c)};DIT_memberListStore.completable=function(a,b){if(a=="")return"*member";return _AC_SimpleStore.prototype.completable.call(this,a,b)};DIT_ownerStore=new _AC_SimpleStore(b);
DIT_ownerStore.docstrings=c;DIT_ownerStore.commaCompletes=!1;DIT_ownerStore.substitute=function(a,b,c,d){return d.value};DIT_ownerStore.completions=function(b,c){var d=DIT_fullComplete(b,a);if(d)return d;return _AC_SimpleStore.prototype.completions.call(this,b,c)};DIT_ownerStore.completable=function(a){if(!ac_everTyped)return"*owner";return a}}var DIT_labelWords=[];
function DIT_setUpLabelStore(a){DIT_labelWords=[];for(var b={},c=0;c<a.length;c++){var d=a[c];DIT_labelWords.push(d.name);b[d.name]=d.doc}DIT_labelStore=new _AC_SimpleStore(DIT_labelWords);DIT_labelStore.docstrings=b;DIT_labelStore.commaCompletes=!1;DIT_labelStore.substitute=function(a,b,c,d){return d.value};DIT_labelStore.completable=function(a,b){if(b==0)return"*label";for(var c=0,d=b;--d>=0;){var h=a.charAt(d);if(h==" "||h==","){c=d+1;break}}d=a.indexOf("?");d>=0&&(a=a.substring(c,d));d=a.substring(c,
b);a.lastIndexOf("-")>0&&!ac_everTyped&&(d=a.substring(c,Math.min(b,a.lastIndexOf("-"))));a.startsWith("Restrict-")&&(d=a,a.lastIndexOf("-")>8&&(d=a.substring(c,Math.min(b,a.lastIndexOf("-")))));return d};DIT_labelStore.completions=function(b,c){var d=DIT_fullComplete(b,a);d==null&&(d=_AC_SimpleStore.prototype.completions.call(this,b,c));for(var i=[],h=0;h<d.length;h++){var k=d[h].value.split("-"),j=k[0].toLowerCase();if(d[h].value.startsWith("Restrict-")){if(!b.toLowerCase().startsWith("r"))continue;
k.length>1&&(j+="-"+k[1].toLowerCase())}if(FindInArray(DIT_exclPrefixes,j)==-1||DIT_usedPrefixes[j]==void 0||DIT_usedPrefixes[j].length==0||DIT_usedPrefixes[j].length==1&&DIT_usedPrefixes[j][0]==ac_focusedInput){var k=!0,l;for(l in DIT_usedPrefixes)for(var j=DIT_usedPrefixes[l],m=0;m<j.length;m++){var n=j[m];n.value.toLowerCase()==d[h].value.toLowerCase()&&n!=ac_focusedInput&&(k=!1)}k&&i.push(d[h])}}return i}}
function DIT_setUpAutoCompleteStore(a){DIT_autoCompleteStore=new _AC_SimpleStore(a);for(var b=[],c=0;c<a.length;++c)b.push({name:a[c],doc:""});DIT_autoCompleteStore.completions=function(a,c){if(a.length>18)return[];var f=DIT_fullComplete(a,b);f==null&&(f=_AC_SimpleStore.prototype.completions.call(this,a,c));for(var g={},i=document.getElementsByTagName("input"),h=0;h<i.length;++h)HasClass(i[h],"autocomplete")&&(g[i[h].value]=!0);i=[];for(h=0;h<f.length;++h)g[f[h].value]||i.push(f[h]);return i};DIT_autoCompleteStore.completable=
function(a){if(a=="")return"*ac";return a};DIT_autoCompleteStore.substitute=function(a,b,c,g){return g.value};DIT_autoCompleteStore.commaCompletes=!1}var DIT_optionsXmlHttp=void 0,DIT_optionsURL=void 0,DIT_optionsRequestHadCCT=void 0;
function DIT_fetchOptions(a,b,c,d,e,f){DIT_autoCompleteFeedName=c;DIT_optionsXmlHttp=XH_XmlHttpCreate();a=a?"/a/"+a:"";b=b?"/p/"+b:"/hosting";DIT_optionsURL=a+b+"/feeds/"+c+"?token="+d;for(var g in f)DIT_optionsURL+="&"+g+"="+encodeURIComponent(f[g]);DIT_optionsRequestHadCCT=!0;XH_XmlHttpGET(DIT_optionsXmlHttp,DIT_optionsURL+"&cct="+e,DIT_issueOptionsFeedCallback)}
function DIT_issueOptionsFeedCallback(){DIT_optionsXmlHttp.readyState==4&&DIT_optionsXmlHttp.status==200&&(DIT_gotIssueOptionsFeed(DIT_optionsXmlHttp.responseText),DIT_optionsRequestHadCCT&&(DIT_optionsRequestHadCCT=!1,XH_XmlHttpGET(DIT_optionsXmlHttp,DIT_optionsURL+"&cct="+Math.round((new Date).getTime()/1E3),DIT_issueOptionsFeedCallback)))}
function DIT_gotIssueOptionsFeed(a){_d=null;try{eval("_d="+a)}catch(b){return null}DIT_setUpStatusStore(_d.open,_d.closed);DIT_setUpSearchStore(_d.labels,_d.members,_d.open,_d.closed);DIT_setUpLabelStore(_d.labels);DIT_setUpMemberStore(_d.members);DIT_exclPrefixes=_d.excl_prefixes;for(var a=DIT_labelFieldIDPrefix,c=0;c<15;c++)DIT_validateLabel($(a+c));DIT_restrict_to_known=_d.strict};function DIT_go(a){document.location=a}function DIT_getColspecElement(){return document.getElementById("colspec_field").firstChild}function DIT_getSearchColspecElement(){return document.getElementById("search_colspec").firstChild}function DIT_getArtifactSearchField(){var a=document.getElementById("qq");return a?a.firstChild:void 0}function DIT_autosizeArtifactSerchField(){var a=DIT_getArtifactSearchField();if(a){var b=a.value.length+3;b>75&&(b=75);if(b>a.size)a.size=b}}
window.setInterval(DIT_autosizeArtifactSerchField,700);function DIT_formatContextQueryArgs(){var a="",b=DIT_getColspecElement().value;_ctxCan!=2&&(a+="&can="+_ctxCan);_ctxQuery!=""&&(a+="&q="+encodeURIComponent(_ctxQuery));_ctxSortspec!=""&&(a+="&sort="+_ctxSortspec);b!=_ctxDefaultColspec&&(a+="&colspec="+b);_ctxStart!=0&&(a+="&start="+_ctxStart);_ctxNum!=_ctxResultsPerPage&&(a+="&num="+_ctxNum);return a}var _PRETOKENIZED_FIELDS=["owner","reporter","cc","commentby"];
function DIT_filterTo(a,b){var c=DIT_getArtifactSearchField().value;c!=""&&(c+=" ");for(var d="=",e=0;e<_PRETOKENIZED_FIELDS.length;e++)if(a==_PRETOKENIZED_FIELDS[e]){d=":";break}c+=a+d+b;c="list?can="+$("can").value+"&q="+c;$("sort")&&$("sort").value&&(c+="&sort="+$("sort").value);c+="&colspec="+DIT_getColspecElement().value;DIT_go(c)}
function DIT_addSort(a,b){var c="";if($("sort"))c=$("sort").value;var c=c.split(/ +/),d=a;b&&(d="-"+a);for(var d=[d],e=0;e<c.length;e++)c[e]!=""&&c[e]!=a&&c[e]!="-"+a&&d.push(c[e]);c="list?can="+$("can").value+"&q="+DIT_getArtifactSearchField().value;c+="&sort="+d.join("+");c+="&colspec="+DIT_getColspecElement().value;DIT_go(c)}function DIT_sortUp(a){DIT_addSort(a,!1)}function DIT_sortDown(a){DIT_addSort(a,!0)};var DIT_cursorStops,DIT_selected=void 0;function DIT_focusArtifactSearchField(){var a=DIT_getArtifactSearchField();a.focus();a.select()}function DIT_closeKeystrokeHelp(){var a=document.getElementById("keys_help");if(a)a.style.display="none"}function DIT_toggleKeystrokeHelp(){var a=document.getElementById("keys_help");a?a.style.display=a.style.display?"":"none":(DIT_helpXmlHttp=XH_XmlHttpCreate(),a="/hosting/issues/keyshelp",XH_XmlHttpGET(DIT_helpXmlHttp,a,DIT_helpCallback))}var DIT_helpXmlHttp=void 0;
function DIT_helpCallback(){if(DIT_helpXmlHttp.readyState==4&&DIT_helpXmlHttp.status==200){var a=DIT_helpXmlHttp.responseText,b=document.getElementById("helparea");if(b)b.innerHTML=a}}
function DIT_setupKibblesComponentKeys(a,b,c){kibbles.keys.addKeyPressListener("/",function(){window.setTimeout(DIT_focusArtifactSearchField,10)});c!="entry"&&kibbles.keys.addKeyPressListener("c",function(){_go(b)});c!="list"&&kibbles.keys.addKeyPressListener("u",function(){DIT_go(a)});kibbles.keys.addKeyPressListener("?",DIT_toggleKeystrokeHelp);kibbles.keys.addKeyPressListener("ESC",DIT_closeKeystrokeHelp);kibbles.keys.addKeyPressListener("ESC",DIT_hideInfoPeek)}
function DIT_openArtifactAtCursor(a){DIT_selected>=0&&DIT_selected<DIT_cursorStops.length&&(a=DIT_cursorStops[DIT_selected].childNodes[a],(a=a.childNodes[0])&&DIT_go(a.getAttribute("href")))}function DIT_updateCursor(a,b){DIT_selected=void 0;b&&(RemoveClass(b.element,"cursor_on"),AddClass(b.element,"cursor_off"),DIT_rowRolloverOff(b.element));if(a&&a.element)RemoveClass(a.element,"cursor_off"),AddClass(a.element,"cursor_on"),DIT_selected=a.index,DIT_rowRolloverOn(a.element)}
function DIT_setupKibblesCursorStops(){kibbles.skipper.addStopListener(kibbles.skipper.LISTENER_TYPE.PRE,DIT_updateCursor);kibbles.skipper.setOption("padding_top",50);kibbles.skipper.setOption("padding_bottom",50);for(var a=[],b=document.getElementById("cursorarea"),c=0;c<b.childNodes.length;c++){var d=b.childNodes[c],e=d.tagName;e&&(e=="TR"||e=="DIV")&&d.className.indexOf("cursor")>=0&&a.push(d)}DIT_cursorStops=a;for(a=0;a<DIT_cursorStops.length;a++)b=DIT_cursorStops[a],kibbles.skipper.append(b),
b.className.indexOf("cursor_on")>=0&&kibbles.skipper.setCurrentStop(a)}function DIT_setupKibblesOnEntryPage(a,b){DIT_setupKibblesComponentKeys(a,b,"entry")}
function DIT_setupKibblesOnListPage(a,b,c,d,e,f,g){DIT_setupKibblesCursorStops(!0);kibbles.skipper.addFwdKey("j");kibbles.skipper.addRevKey("k");kibbles.keys.addKeyPressListener("j",function(){DIT_keepInfoPeekOpen(c,d)});kibbles.keys.addKeyPressListener("k",function(){DIT_keepInfoPeekOpen(c,d)});if(f!=void 0){var i=f;kibbles.keys.addKeyPressListener("x",function(){if(DIT_selected>=0&&DIT_selected<DIT_cursorStops.length){var a=DIT_cursorStops[DIT_selected].childNodes[i];if(a=a.childNodes[0])a.checked=
a.checked?"":"checked"}});kibbles.keys.addKeyPressListener("s",function(){if(DIT_selected>=0&&DIT_selected<DIT_cursorStops.length){for(var a=DIT_cursorStops[DIT_selected].childNodes[i],a=a.firstChild;a&&a.tagName!="IMG";)a=a.nextSibling;a&&_toggleStar(a,c,d,issueIds[DIT_selected],g)}})}kibbles.keys.addKeyPressListener("o",function(){DIT_openArtifactAtCursor(e)});kibbles.keys.addKeyPressListener("enter",function(){DIT_openArtifactAtCursor(e)});kibbles.keys.addKeyPressListener("h",function(){var a=
c,b=d;$("infobubble").style.display?DIT_hideInfoPeek():(DIT_selected==void 0&&kibbles.skipper.setCurrentStop(0),DIT_showInfoPeek(a,b,DIT_selected))});kibbles.keys.addKeyPressListener("f",DIT_firstComment);kibbles.keys.addKeyPressListener("p",DIT_prevComment);kibbles.keys.addKeyPressListener("n",DIT_nextComment);kibbles.keys.addKeyPressListener("l",DIT_lastComment);DIT_setupKibblesComponentKeys(a,b,"list")}
function DIT_setupKibblesOnDetailPage(a,b,c,d,e,f,g,i,h,k){DIT_setupKibblesCursorStops(!1);kibbles.skipper.addFwdKey("n");kibbles.skipper.addRevKey("p");c&&kibbles.keys.addKeyPressListener("k",function(){DIT_go(c)});d&&kibbles.keys.addKeyPressListener("j",function(){DIT_go(d)});i&&kibbles.keys.addKeyPressListener("r",function(){window.setTimeout("_openIssueUpdateForm()",10)});h&&kibbles.keys.addKeyPressListener("s",function(){var a=document.getElementById("star");DIT_toggleStar(a,e,f,g,k);DIT_syncStarIcons(a,
"star2")});DIT_setupKibblesComponentKeys(a,b,"detail")};var DIT_peekXmlHttp=void 0,DIT_nextPeekXmlHttp=void 0,DIT_peekRow=void 0,DIT_seenPeeks={};function DIT_hideInfoPeek(){var a=$("infobubble");a.style.display="";a.style.left="-2000px"}
function DIT_showInfoPeek(a,b,c){DIT_peekRow=c;c=issueIds[DIT_peekRow];a=(a?"/a/"+a:"")+"/p/"+b;a=a+"/issues/peek?id="+c;$("peekarea").innerHTML=DIT_seenPeeks[DIT_peekRow]||'<div class="loading">Loading...</div>';DIT_commentNavEl=void 0;DIT_peekXmlHttp=XH_XmlHttpCreate();XH_XmlHttpGET(DIT_peekXmlHttp,a,DIT_peekCallback);a=nodeBounds(DIT_cursorStops[DIT_peekRow]);b=$("infobubble");b.style.display="block";c=a.y+a.h+0;b.style.top=c+"px";c=nodeBounds(b);if(c.y+c.h>window.pageYOffset+window.innerHeight&&
(c=a.y-c.h-0,c>=window.pageYOffset))b.style.top=c+"px";b.style.left="110px"}function DIT_peekCallback(){if(DIT_peekXmlHttp.readyState==4&&DIT_peekXmlHttp.status==200){var a=DIT_peekXmlHttp.responseText;$("peekarea").innerHTML=a;DIT_seenPeeks[DIT_peekRow]=a;DIT_peekRow+1<issueIds.length&&!DIT_seenPeeks[DIT_peekRow+1]&&(a=issueIds[DIT_peekRow+1],a="peek?id="+a,DIT_nextPeekXmlHttp=XH_XmlHttpCreate(),XH_XmlHttpGET(DIT_nextPeekXmlHttp,a,DIT_nextPeekCallback))}}
function DIT_nextPeekCallback(){if(DIT_nextPeekXmlHttp.readyState==4&&DIT_nextPeekXmlHttp.status==200)DIT_seenPeeks[DIT_peekRow+1]=DIT_nextPeekXmlHttp.responseText}function DIT_keepInfoPeekOpen(a,b){var c=$("infobubble");c.style.display!=""&&DIT_showInfoPeek(a,b,DIT_selected)}var DIT_commentNavEl=void 0;function DIT_scrollToPeekComment(a){a=a.offsetTop;$("issuecomments").scrollTop=a-30}function DIT_findNextCommentElement(a){for(;a&&(!a.id||a.id.substr(0,2)!="hc");)a=a.nextSibling;return a}
function DIT_findPrevCommentElement(a){for(;a&&(!a.id||a.id.substr(0,2)!="hc");)a=a.previousSibling;return a}function DIT_nextComment(){var a;DIT_commentNavEl==void 0?(a=$("issuecomments").firstChild,a=DIT_findNextCommentElement(a),a=a.nextSibling):a=DIT_commentNavEl.nextSibling;if(a=DIT_findNextCommentElement(a))DIT_commentNavEl=a,DIT_scrollToPeekComment(DIT_commentNavEl)}
function DIT_prevComment(){var a;a=DIT_commentNavEl==void 0?$("issuecomments").lastChild:DIT_commentNavEl.previousSibling;if(a=DIT_findPrevCommentElement(a))DIT_commentNavEl=a,DIT_scrollToPeekComment(DIT_commentNavEl)}function DIT_firstComment(){DIT_commentNavEl=$("issuecomments").firstChild;DIT_commentNavEl=DIT_findNextCommentElement(DIT_commentNavEl);DIT_scrollToPeekComment(DIT_commentNavEl)}
function DIT_lastComment(){DIT_commentNavEl=$("issuecomments").lastChild;DIT_commentNavEl=DIT_findPrevCommentElement(DIT_commentNavEl);DIT_scrollToPeekComment(DIT_commentNavEl)};function DIT_onload(){_ac_install();_ac_register(function(a){if(a.id.startsWith("search"))return DIT_searchStore;if(a.id.startsWith("quickedit"))return DIT_searchStore;if(a.id.startsWith("label"))return DIT_labelStore;if(a.id.startsWith("status"))return DIT_statusStore;if(a.id.startsWith("member"))return DIT_memberListStore;if(a.id.startsWith("owner"))return DIT_ownerStore;if(a.className.indexOf("autocomplete")!=-1)return DIT_autoCompleteStore});_PC_Install();DIT_allColumnNames=_allColumnNames;DIT_labelFieldIDPrefix=
_lfidprefix;DIT_allOrigLabels=_allOrigLabels}_hideID=DIT_hideID;_showID=DIT_showID;_hideEl=DIT_hideEl;_showEl=DIT_showEl;_showInstead=DIT_showInstead;_selectAllIssues=DIT_selectAllIssues;_selectNoneIssues=DIT_selectNoneIssues;_toggleHidden=DIT_toggleHidden;_toggleCollapse=DIT_toggleCollapse;_toggleRows=DIT_toggleRows;_toggleColumn=DIT_toggleColumn;_toggleColumnUpdate=DIT_toggleColumnUpdate;_addcol=DIT_addColumn;_checkRangeSelect=DIT_checkRangeSelect;_makeIssueLink=DIT_makeIssueLink;_setRowLinks=DIT_setRowLinks;
_onload=DIT_onload;_MoreActions_onchange=DIT_MoreActions_onchange;_fetchOptions=DIT_fetchOptions;_setACOptions=DIT_setUpAutoCompleteStore;_openIssueUpdateForm=DIT_openIssueUpdateForm;_addAttachmentFields=DIT_addAttachmentFields;_acstore=_AC_SimpleStore;_accomp=_AC_Completion;_acreg=_ac_register;_go=DIT_go;_formatContextQueryArgs=DIT_formatContextQueryArgs;_ctxArgs="";_ctxResultsPerPage=_ctxNum=_ctxStart=_ctxDefaultColspec=_ctxSortspec=_ctxQuery=_ctxCan=void 0;_filterTo=DIT_filterTo;_sortUp=DIT_sortUp;
_sortDown=DIT_sortDown;_closeAllPopups=DIT_closeAllPopups;_closeSubmenus=DIT_closeSubmenus;_showRight=DIT_showRight;_showBelow=DIT_showBelow;_highlightRow=DIT_highlightRow;_highlightRowCallback=DIT_highlightRowCallback;_floatMetadata=DIT_floatMetadata;_floatVertically=DIT_floatVertically;_selectPrompt=DIT_selectPrompt;_savePrompt=DIT_savePrompt;_newPrompt=DIT_newPrompt;_deletePrompt=DIT_deletePrompt;_switchPrompt=DIT_switchPrompt;_promptNames=DIT_promptNames;_toggleStar=DIT_toggleStar;
_syncStarIcons=DIT_syncStarIcons;_toggleStarLocal=DIT_toggleStarLocal;_rowRolloverOn=DIT_rowRolloverOn;_rowRolloverOff=DIT_rowRolloverOff;_confirmNovelStatus=DIT_confirmNovelStatus;_confirmNovelLabel=DIT_confirmNovelLabel;_vallab=DIT_validateLabel;_dirty=DIT_dirty;_exposeExistingLabelFields=DIT_exposeExistingLabelFields;_confirmDiscardEntry=DIT_confirmDiscardEntry;_confirmDiscardUpdate=DIT_confirmDiscardUpdate;_allOrigLabels=_lfidprefix=void 0;_checkPlusOne=DIT_checkPlusOne;_checkUnrestrict=DIT_checkUnrestrict;
_clearOnFirstEvent=DIT_clearOnFirstEvent;_forceProperTableWidth=DIT_forceProperTableWidth;_RC=RemoveClass;_acof=_ac_onfocus;_acmo=_ac_mouseover;_acse=_ac_select;_acrob=_ac_real_onblur;_allColumnNames=[];_getColspec=DIT_getColspecElement;_getSearchColspec=DIT_getSearchColspecElement;navigator.userAgent.toLowerCase().indexOf("webkit")!=-1&&(document.addEventListener("click",_ac_fake_onblur,!1),document.captureEvents&&document.captureEvents(Event.CLICK));_setPeoplePrefs=DIT_setPeoplePrefs;
_setupKibblesOnEntryPage=DIT_setupKibblesOnEntryPage;_setupKibblesOnListPage=DIT_setupKibblesOnListPage;_setupKibblesOnDetailPage=DIT_setupKibblesOnDetailPage;_showInfoPeek=DIT_showInfoPeek;_hideInfoPeek=DIT_hideInfoPeek;_firstComment=DIT_firstComment;_prevComment=DIT_prevComment;_nextComment=DIT_nextComment;_lastComment=DIT_lastComment;function _ac_install(){ac_addHandler_(document.body,"onkeydown",ac_keyevent_);ac_addHandler_(document.body,"onkeypress",ac_keyevent_)}function _ac_register(a){for(var b=ac_storeConstructors.length;--b>=0;)if(ac_storeConstructors[b]===a)return;ac_storeConstructors.push(a)}function _ac_onfocus(a){ac_keyevent_(a)}function _ac_isCompleting(){return!!ac_store&&!ac_suppressCompletions}function _ac_isCompleteListShowing(){return!!ac_store&&!ac_suppressCompletions&&ac_completions&&ac_completions.length}
function _ac_cancel(){ac_suppressCompletions=!0;ac_updateCompletionList(!1)}function ac_addHandler_(a,b,c){var d=a[b];a[b]=d?ac_fnchain_(a[b],c):c;return d}function ac_cancelEvent_(a){"stopPropagation"in a?a.stopPropagation():a.cancelBubble=!0;"preventDefault"in a&&a.preventDefault()}function ac_fnchain_(a,b){return function(){var c=a.apply(this,arguments),d=b.apply(this,arguments);return c===!1||d===!1?!1:!0}}
function ac_keyevent_(a){var a=a||window.event,b=a.target||a.srcElement;if("INPUT"==b.tagName&&b.type.match(/^text$/i)||"TEXTAREA"==b.tagName){var c=GetKeyCode(a),d=a.type=="keydown",e=a.shiftKey,f=!0;if(b!==ac_focusedInput||ac_store===null)if(ac_focusedInput=b,f=!1,13!==c&&27!==c){for(var g=0;g<ac_storeConstructors.length;++g){var i=ac_storeConstructors[g](b,a);if(i){ac_store=i;ac_oldBlurHandler=ac_addHandler_(ac_focusedInput,"onblur",_ac_ob);f=!0;break}}f||_ac_ob(null)}if(f){b=ac_store.isCompletionKey(c,
d,e);f=ac_completions&&ac_completions.length>0;g=!1;if(b&&f)g=!ac_suppressCompletions&&!!ac_completions&&ac_selected!=-1,window.setTimeout(function(){ac_store&&ac_handleKey_(c,d,e)},0);else if(b){if(ac_store.oncomplete)ac_store.oncomplete(!1,c,ac_focusedInput,void 0)}else g=c==27||c==40||c==38,window.setTimeout(function(){ac_store&&ac_handleKey_(c,d,e)},0);g&&ac_cancelEvent_(a);return!g}}return!0}function _ac_ob(a){navigator.userAgent.toLowerCase().indexOf("webkit")!=-1||_ac_real_onblur(a)}
function _ac_real_onblur(){if(ac_focusedInput)ac_focusedInput.onblur=ac_oldBlurHandler;ac_focusedInput=ac_store=null;ac_everTyped=!1;ac_oldBlurHandler=null;ac_suppressCompletions=!1;ac_updateCompletionList(!1)}function _ac_fake_onblur(a){var b;if(!a)a=window.event;if(a.target)b=a.target;else if(a.srcElement)b=a.srcElement;if(b.nodeType==3)b=b.parentNode;"INPUT"!=b.nodeName&&_ac_real_onblur(a)}function _AC_Store(){}_AC_Store.prototype.completable=function(){alert("UNIMPLEMENTED completable")};
_AC_Store.prototype.completions=function(){alert("UNIMPLEMENTED completions")};_AC_Store.prototype.oncomplete=function(a,b,c){if(c.onkeyup)c.onkeyup(void 0)};_AC_Store.prototype.substitute=function(){alert("UNIMPLEMENTED substitute")};_AC_Store.prototype.commaCompletes=!0;_AC_Store.prototype.isCompletionKey=function(a,b){if(!b&&(13===a||AC_COMMA_KEYCODE==a&&this.commaCompletes))return!0;return!1};
function _AC_SimpleStore(a){this.firstCharMap_={};for(var b=0;b<a.length;++b){var c=a[b];if(c)for(var d=c.split(/\W+/),e=0;e<d.length;++e)if(d[e]){var f=d[e].charAt(0).toLowerCase(),g=this.firstCharMap_[f];if(g){if(g[g.length-1].value==c)continue}else g=this.firstCharMap_[f]=[];g.push(new _AC_Completion(c,null,""))}}this.countThreshold=2500;this.docstrings={}}_AC_SimpleStore.prototype=new _AC_Store;_AC_SimpleStore.prototype.constructor=_AC_SimpleStore;
_AC_SimpleStore.prototype.completable=function(a,b){for(var c=0,d=0,e=0;e<b;++e){var f=a.charAt(e);switch(d){case 0:if('"'==f)d=1;else if(","==f||" "==f)c=e+1;break;case 1:'"'==f&&(d=0)}}for(;c<b&&" \t\r\n".indexOf(a.charAt(c))>=0;)++c;return a.substring(c,b)};
_AC_SimpleStore.prototype.completions=function(a,b){if(!a)return[];var c=RegExp("^(.*[\\s<\"',:-=])?("+a.replace(/([\^*+\-\$\\\{\}\(\)\[\]\#?\.])/g,"\\$1")+")(.*)","i");if((!b||!b.length)&&a)b=this.firstCharMap_[a.charAt(0).toLowerCase()];var d=[];if(b)for(var e=0;e<b.length;++e){var f=b[e].value.match(c);if(f&&(d.push(new _AC_Completion(b[e].value,ac_preTextToHtml(f[1]||"")+"<b>"+ac_preTextToHtml(f[2])+"</b>"+ac_preTextToHtml(f[3]),this.docstrings[b[e].value])),d.length>this.countThreshold))break}return d};
_AC_SimpleStore.prototype.autoselectFirstRow=function(){return!0};function _AC_CompareACCompletion(a,b){var c=a.value.toLowerCase().replace(/^\W*/,""),d=b.value.toLowerCase().replace(/^\W*/,"");return a.value===b.value?0:c<d?-1:1}_AC_SimpleStore.prototype.substitute=function(a,b,c,d){return a.substring(0,b-c.length)+d.value+", "+a.substring(b)};function _AC_Completion(a,b,c){this.value=a;this.html=b;this.dochtml=ac_preTextToHtml(c)}
_AC_Completion.prototype.toString=function(){return"(AC_Completion: "+this.value+")"};var ac_storeConstructors=[],ac_focusedInput=null,ac_store=null,ac_oldBlurHandler=null,ac_suppressCompletions=!1,ac_lastCompletable=null,ac_completions=null,ac_selected=-1;
function ac_handleKey_(a,b,c){ac_checkCompletions();var d=!0,e=ac_completions?ac_completions.length:0;if(ac_store.isCompletionKey(a,b,c)){if(ac_selected<0&&e>=1&&ac_store.autoselectFirstRow()&&(ac_selected=0),ac_selected>=0&&(b=ac_focusedInput,c=ac_completions[ac_selected].value,ac_complete(),ac_store.oncomplete))ac_store.oncomplete(!0,a,b,c)}else{switch(a){case 27:ac_selected=-1;d=!1;break;case 38:b&&(ac_selected=Math.max(e>=0?0:-1,ac_selected-1));break;case 40:b&&(ac_selected=Math.min(e-1,ac_selected+
1))}if(b)switch(a){case 27:case 13:case 38:case 40:case 39:case 37:case 9:case 16:case 8:case 46:break;default:ac_everTyped=!0}}ac_focusedInput&&ac_updateCompletionList(d)}function _ac_select(a){ac_selected=a;ac_complete();if(ac_store.oncomplete)ac_store.oncomplete(!0,null,ac_focusedInput,ac_focusedInput.value);ac_checkCompletions();ac_updateCompletionList(!0)}function _ac_mouseover(a){ac_selected=a;ac_updateCompletionList(!0)}
function ac_complete(){var a=ac_getCaretPosition_(ac_focusedInput),b=ac_completions[ac_selected];ac_focusedInput.value=ac_store.substitute(ac_focusedInput.value,a,ac_lastCompletable,b);a=a-ac_lastCompletable.length+b.value.length;b.value.substring(b.value.length-1)!=":"&&a++;ac_selected=-1;ac_lastCompletable=ac_completions=null;ac_everTyped=!1;var b=window,c=ac_focusedInput;IsDefined(c.selectionEnd)&&IsDefined(c.selectionStart)?(c.selectionStart=a,c.selectionEnd=a):b.document.selection&&c.createTextRange&&
(b=c.createTextRange(),b.collapse(!0),b.move("character",a),b.select())}var ac_everTyped=!1;
function ac_checkCompletions(){if(ac_suppressCompletions)ac_completions=ac_lastCompletable=null,ac_selected=-1;else{var a=ac_getCaretPosition_(ac_focusedInput),a=ac_store.completable(ac_focusedInput.value,a);if(a!=ac_lastCompletable){var b;ac_lastCompletable&&ac_lastCompletable.length<a.length&&a.substring(0,ac_lastCompletable.length)==ac_lastCompletable?b=ac_completions:(ac_completions=null,ac_selected=-1);var c=ac_selected>=0?ac_completions[ac_selected].value:null;ac_completions=ac_store.completions(a,
b);ac_selected=-1;for(b=0;b<ac_completions.length;++b)if(c==ac_completions[b].value){ac_selected=b;break}ac_lastCompletable=a}}}
function ac_updateCompletionList(a){var b=document.getElementById("ac-list");if(a&&ac_completions&&ac_completions.length){if(!b)b=document.createElement("DIV"),b.id="ac-list",b.style.position="absolute",b.style.display="none",document.body.appendChild(b);ac_selected<0&&ac_store&&ac_store.autoselectFirstRow()&&(ac_selected=0);var a=[],c=0;a.push("<table cellpadding=0 cellspacing=0>");for(var d=0;d<ac_completions.length;++d)if(ac_completions[d].heading)a.push("<tr><th colspan=2>"),c&&a.push("<br/>"),
a.push(ac_completions[d].heading,"</th></tr>"),c++;else{var e="onmousedown";navigator.userAgent.toLowerCase().indexOf("webkit")!=-1&&(e="onmouseup");a.push("<tr ",e,'="try{_acse(',d,')}finally{return false}"','onmouseover="_acmo(',d,')"',d==ac_selected?' id="ac-selected-row" class=selected>':">","<td>","&nbsp;",ac_completions[d].html);a.push("</td><td>&nbsp;");ac_completions[d].dochtml&&a.push("= ",ac_completions[d].dochtml);a.push("</td></tr>")}a.push("</table>");b.innerHTML=a.join("");a=nodeBounds(ac_focusedInput);
b.style.left=a.x+"px";b.style.top=a.y+a.h+"px";b.style.display="";window.setTimeout(ac_autoscroll,100)}else if(b)b.style.display="none",b.innerHTML=""}function ac_autoscroll(){var a=document.getElementById("ac-list"),b=document.getElementById("ac-selected-row"),c=b?b.offsetTop:0,d=b?b.offsetHeight:0;if(a&&b)if(c<a.scrollTop)a.scrollTop=c-8;else if(c+d+8>a.scrollTop+a.offsetHeight)a.scrollTop=c+d-a.offsetHeight+8}
function ac_preTextToHtml(a){return a.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/\"/g,"&quot;").replace(/ /g,"&nbsp;").replace(/\r\n?|\n/g,"<br>")}
function ac_getCaretPosition_(a){if("INPUT"==a.tagName){var b=a.value.length;if(void 0!=a.selectionStart){if(b=a.selectionEnd,a.id.startsWith("status"))b=a.selectionStart}else if(document.selection){var c=document.selection.createRange(),d=c.text.length;c.moveStart("character",-b);b=c.text.length;a.id.startsWith("status")&&(b=c.text.length-d)}return b}else return GetCursorPos(window,a)}var AC_COMMA_KEYCODE=",".charCodeAt(0);})()
